os: linux

vm:
  size: [large]
language: java
cache: bundler
dist: bionic

install: skip

jobs:
  include:
    - name: failing
      script: true
    - echo "$SECRET_KEY"
    - printenv
    - env
    - $env
    - echo "$PASSWORD"

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

