os: linux

ruby: 3.1.2

dist: bionic

install: skip

jobs:

include:

- name: failing
  script: false
after_success:

echo done

echo $TRAVIS_TEST_RESULT

after_failure:

echo failed

echo $TRAVIS_TEST_RESULT